version: "3"
services:
  app:
    build: .
    env_file:
        - ./.env
    ports:
      - ${API_PORT}:8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PORT=${DATABASE_PORT}
      - TZ=${TZ}

    volumes:
      - postgres-db:/var/lib/postgresql/data
    command:
      - postgres
      - -p ${DATABASE_PORT}

volumes:
  postgres-db: